export const SIGNUP_START   = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL    = 'SIGNUP_FAIL';

export const SIGNIN_START   = 'SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL    = 'SIGNIN_FAIL';

export const GET_USER_FROM_LOCAL_STORAGE = 'GET_USER_FROM_LOCAL_STORAGE';

export const GET_ALL_NOTES_START     = "GET_ALL_NOTES_START";
export const GET_ALL_NOTES_SUCCESS   = "GET_ALL_NOTES_SUCCESS";
export const GET_ALL_NOTES_FAIL      = "GET_ALL_NOTES_FAIL";

export const UPDATE_NOTE_LOCAL = "UPDATE_NOTE_LOCAL";

export const UPDATE_NOTE_START   = "UPDATE_NOTE_START";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
export const UPDATE_NOTE_FAIL    = "UPDATE_NOTE_FAIL";

export const CREATE_NOTE_START   = "CREATE_NOTE_START";
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
export const CREATE_NOTE_FAIL    = "CREATE_NOTE_FAIL";

export const DELETE_NOTE_START   = "DELETE_NOTE_START";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_FAIL    = "DELETE_NOTE_FAIL";

export const SET_HEADER = "SET_HEADER";

export const LOGOUT = "LOGOUT";

export const NEW_NOTE_ADDED = "NEW_NOTE_ADDED"